### ISSUE TITLE
[visq_unittest] Failure

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#11132]
I get lots of errors in this test in my local environment
```
116/117 Test #116: visq_unittest ..............................***Failed    0.27 sec
....EEEEE...
======================================================================
ERROR: test_MPEIR (test.testQErrorComputer.VisqQErrorComputerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/.../visq-unittest/test/testQErrorComputer.py", line 86, in test_MPEIR
    qmap = computer.run()
  File "/.../visq-unittest/visqlib/QErrorComputer.py", line 131, in run
    self.advance_on(self._fp32_dir, self._fq_dir)
  File "/.../visq-unittest/visqlib/QErrorComputer.py", line 96, in advance_on
    data_paths = self.collect_data_path(fp32_dir, fq_dir)
  File "/.../visq-unittest/visqlib/QErrorComputer.py", line 52, in collect_data_path
    with open(Path(fp32_dir) / 'tensors.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpf1gttxcc/tensors.json'

...

----------------------------------------------------------------------
Ran 12 tests in 0.064s
```

**Comment by seanshpark** [comment]
@jinevening , can you please check this?

**Comment by jinevening** [comment]
> in my local environment

The test passes in my environment. Could you explain your environment? Guessing from the error message, something is wrong with temporary directory. Did you run the test where `/tmp` is not accessible?

**Comment by seanshpark** [comment]
> Did you run the test where /tmp is not accessible?

I think so...
```
drwxrwxrwt   1 root root 12288 Jul 20 00:32 tmp/
```
There wasn't any problems some days ago but suddenly today fails.

**Comment by jinevening** [comment]
Hmm.. Could you remove the build directory of `visq` and `visq-unittest` and rebuild? Recently `visq` was updated, but the change might have not applied to your environment.

**Comment by seanshpark** [comment]
Delete - build was the solution!
Thanks!
