### ISSUE TITLE
[onert/tests] `nnfw_api_gtest` failed 

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE#12702]
git commit tip: `79ca151ddbfa27416a863abda956c0c0e27eda55`

```
[ RUN      ] GenModelTrain.OneOp_Conv2D
nnfw_api_gtest: /home/dragon/github/YongseopKim/ONE/externals/TENSORFLOW-2.8.0-EIGEN/unsupported/Eigen/CXX11/src/Tensor/TensorMorphing.h:148: Eigen::TensorEvaluator<const Eigen::TensorReshapingOp<NewDimensions, XprType>, Device>::TensorEvaluator(const XprType&, const Device&) [with NewDimensions = const Eigen::DSizes<long int, 1>; ArgType = const Eigen::TensorMap<Eigen::Tensor<const float, 1, 1, long int>, 16, Eigen::MakePointer>; Device = Eigen::DefaultDevice; Eigen::TensorEvaluator<const Eigen::TensorReshapingOp<NewDimensions, XprType>, Device>::XprType = Eigen::TensorReshapingOp<const Eigen::DSizes<long int, 1>, const Eigen::TensorMap<Eigen::Tensor<const float, 1, 1, long int>, 16, Eigen::MakePointer> >]: Assertion `internal::array_prod(m_impl.dimensions()) == internal::array_prod(op.dimensions())' failed.
[1]    537122 IOT instruction (core dumped)  ./Product/out/unittest/nnfw_api_gtest
```

**Comment by YongseopKim** [comment]
```
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737311093184) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737311093184) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737311093184, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7842476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff78287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff782871b in __assert_fail_base (fmt=0x7ffff79dd130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7fffafef6210 "internal::array_prod(m_impl.dimensions()) == internal::array_prod(op.dimensions())",
    file=0x7fffafef6190 "/home/dragon/github/YongseopKim/ONE/externals/TENSORFLOW-2.8.0-EIGEN/unsupported/Eigen/CXX11/src/Tensor/TensorMorphing.h", line=148, function=<optimized out>) at ./assert/assert.c:92
#6  0x00007ffff7839e96 in __GI___assert_fail (assertion=0x7fffafef6210 "internal::array_prod(m_impl.dimensions()) == internal::array_prod(op.dimensions())",
    file=0x7fffafef6190 "/home/dragon/github/YongseopKim/ONE/externals/TENSORFLOW-2.8.0-EIGEN/unsupported/Eigen/CXX11/src/Tensor/TensorMorphing.h", line=148,
    function=0x7fffafef5f50 "Eigen::TensorEvaluator<const Eigen::TensorReshapingOp<NewDimensions, XprType>, Device>::TensorEvaluator(const XprType&, const Device&) [with NewDimensions = const Eigen::DSizes<long int, 1>; ArgType ="...) at ./assert/assert.c:101
#7  0x00007fffafc31f42 in Eigen::TensorEvaluator<Eigen::TensorReshapingOp<Eigen::DSizes<long, 1> const, Eigen::TensorMap<Eigen::Tensor<float const, 1, 1, long>, 16, Eigen::MakePointer> const> const, Eigen::DefaultDevice>::TensorEvaluator (this=0x7fffffffce78, op=..., device=...) at /home/dragon/github/YongseopKim/ONE/externals/TENSORFLOW-2.8.0-EIGEN/unsupported/Eigen/CXX11/src/Tensor/TensorMorphing.h:148
#8  0x00007fffafc30c17 in Eigen::TensorEvaluator<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 16, Eigen::MakePointer>, Eigen::TensorReshapingOp<Eigen::DSizes<long, 1> const, Eigen::TensorMap<Eigen::Tensor<float const, 1, 1, long>, 16, Eigen::MakePointer> const> const> const, Eigen::DefaultDevice>::TensorEvaluator (this=0x7fffffffce60, op=..., device=...)
    at /home/dragon/github/YongseopKim/ONE/externals/TENSORFLOW-2.8.0-EIGEN/unsupported/Eigen/CXX11/src/Tensor/TensorAssign.h:131
#9  0x00007fffafc2fc5d in Eigen::internal::TensorExecutor<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 16, Eigen::MakePointer>, Eigen::TensorReshapingOp<Eigen::DSizes<long, 1> const, Eigen::TensorMap<Eigen::Tensor<float const, 1, 1, long>, 16, Eigen::MakePointer> const> const> const, Eigen::DefaultDevice, true, (Eigen::internal::TiledEvaluation)0>::run (expr=..., device=...)
    at /home/dragon/github/YongseopKim/ONE/externals/TENSORFLOW-2.8.0-EIGEN/unsupported/Eigen/CXX11/src/Tensor/TensorExecutor.h:132
#10 0x00007fffafc2f27b in Eigen::TensorBase<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 16, Eigen::MakePointer>, 1>::operator=<Eigen::TensorReshapingOp<Eigen::DSizes<long, 1> const, Eigen::TensorMap<Eigen::Tensor<float const, 1, 1, long>, 16, Eigen::MakePointer> const> > (this=0x7fffffffd0b0, other=...) at /home/dragon/github/YongseopKim/ONE/externals/TENSORFLOW-2.8.0-EIGEN/unsupported/Eigen/CXX11/src/Tensor/TensorBase.h:1177
#11 0x00007fffafc2e976 in nnfw::cker::functor::ReduceOuterDimensions<Eigen::ThreadPoolDevice, float, float, float, Eigen::internal::scalar_sum_op<float, float> >::operator()<2> (this=0x7fffffffd153, device=..., input_dims=...,
    input=..., output=0x7fffffffd1a0) at /home/dragon/github/YongseopKim/ONE/compute/cker/include/cker/eigen/redux_functor.h:57
#12 0x00007fffafc2dde7 in nnfw::cker::functor::biasReductionHelper (input_backprop_buffer=0x555555b9d060, input_backprop_shape=..., bias_grad_buffer=0x555555bb0e90, bias_grad_shape=...)
    at /home/dragon/github/YongseopKim/ONE/compute/cker/include/cker/eigen/redux_functor.h:212
#13 0x00007fffafc2e2c2 in onert::backend::train::ops::biasGrad (input_backprop=0x555555b8ff20, bias_grad=0x555555bb0940) at /home/dragon/github/YongseopKim/ONE/runtime/onert/backend/train/ops/OperationUtils.cc:78
#14 0x00007fffafa93ab1 in onert::backend::train::ops::ConvolutionLayer::backwardFloat32 (this=0x555555b9aae0) at /home/dragon/github/YongseopKim/ONE/runtime/onert/backend/train/ops/ConvolutionLayer.cc:199
#15 0x00007fffafa9330c in onert::backend::train::ops::ConvolutionLayer::backward (this=0x555555b9aae0) at /home/dragon/github/YongseopKim/ONE/runtime/onert/backend/train/ops/ConvolutionLayer.cc:124
#16 0x00007ffff732fbcc in onert::exec::train::TrainableFnSequence::backward (this=0x555555b81990, training_step=0) at /home/dragon/github/YongseopKim/ONE/runtime/onert/core/src/exec/train/TrainableFnSequence.cc:38
#17 0x00007ffff732c41f in onert::exec::train::TrainableExecutor::backwardImpl (this=0x555555b1e300, training_step=0) at /home/dragon/github/YongseopKim/ONE/runtime/onert/core/src/exec/train/TrainableExecutor.cc:171
#18 0x00007ffff732c27e in onert::exec::train::TrainableExecutor::backward (this=0x555555b1e300, training_step=0) at /home/dragon/github/YongseopKim/ONE/runtime/onert/core/src/exec/train/TrainableExecutor.cc:150
#19 0x00007ffff732d9a4 in onert::exec::train::TrainableExecutors::train (this=0x555555ba95c0, desc=..., training_step=0) at /home/dragon/github/YongseopKim/ONE/runtime/onert/core/src/exec/train/TrainableExecutors.cc:75
```

**Comment by YongseopKim** [comment]
duplicated to https://github.com/Samsung/ONE/issues/12678#issuecomment-1968095904
