### ISSUE TITLE
[infra] Python formatter yapf 0.22 is not working with python 3.12

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#13911]
We are using yapf 0.22, but it is not working with python 3.12
3.12 is default python version in ubuntu 24.04

```
$ pip install yapf==0.22.0 --break-system-packages
$ yapf --version
Traceback (most recent call last):
  File "/home/hseok82/.local/bin/yapf", line 5, in <module>
    from yapf import run_main
  File "/home/hseok82/.local/lib/python3.12/site-packages/yapf/__init__.py", line 36, in <module>
    from yapf.yapflib import file_resources
  File "/home/hseok82/.local/lib/python3.12/site-packages/yapf/yapflib/file_resources.py", line 24, in <module>
    from lib2to3.pgen2 import tokenize
ModuleNotFoundError: No module named 'lib2to3'
```

In python 3.12, latest version 0.40.2 is working, but formatting result is different: 199 files

**Comment by seanshpark** [comment]
> In python 3.12, latest version 0.40.2 is working,

0.40.2 exists for py3.8 and py3.10

> but formatting result is different: 199 files

let's go with file change in single PR :)
