### ISSUE TITLE
[circle-quantizer] Invalid intermediate model after fake-quantization

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#14477]
## What

When I ran circle-quantizer with this model, I found an error where luci-interpreter failed while running record-minmax with fake-quantized model. 

Before doing fake-quantization, the model runs well. But, after fake-quantization, luci-interpreter failed.

```bash
#1  0x00007ffff7395859 in __GI_abort () at abort.c:79
#2  0x00007ffff7cd40a9 in void tflite::reference_ops::BroadcastMul4DSlow<float>(tflite::ArithmeticParams const&, tflite::RuntimeShape const&, float const*, tflite::RuntimeShape const&, float const*, tflite::RuntimeShape const&, float*) ()
   from /usr/share/one/bin/../lib/libluci_interpreter.so
#3  0x00007ffff7cce3d5 in luci_interpreter::kernels::Mul::evalFloat() const () from /usr/share/one/bin/../lib/libluci_interpreter.so
#4  0x00007ffff7c16058 in luci_interpreter::RuntimeGraph::execute() const () from /usr/share/one/bin/../lib/libluci_interpreter.so
#5  0x00005555555701c5 in ?? ()
#6  0x000055555555f4e8 in ?? ()
#7  0x000055555555d9e0 in ?? ()
#8  0x00007ffff7397083 in __libc_start_main (main=0x55555555d9d0, argc=15, argv=0x7fffffffdc68, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdc58) at ../csu/libc-start.c:308
#9  0x000055555555da6e in ?? ()
```

[test.zip](https://github.com/user-attachments/files/18181084/test.zip)

**Comment by seanshpark** [comment]
@mhs4670go , can you give command line to reproduce this?

**Comment by mhs4670go** [comment]
Hmmm.. turned out that it's a bit hard to be reproduced and it might be not quantizer's bug. I'll post an issue in the internal repo.
