### ISSUE TITLE
[gen_golden] error on float input

### ISSUE THREAD

**Issue by glistening** [Samsung/ONE#2761]
`gen_golden` fails for tflite in [onehot_offvalue_from_input.zip](https://github.com/Samsung/ONE/files/4856084/onehot_offvalue_from_input.zip)

```
root@white:/opt/z/ONE# tools/nnpackage_tool/gen_golden/gen_golden.py onehot_offvalue_from_input.tflite
Traceback (most recent call last):
  File "tools/nnpackage_tool/gen_golden/gen_golden.py", line 150, in <module>
    interpreter.set_tensor(input_details[idx]['index'], input_values[idx])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py", line 404, in set_tensor
    self._interpreter.SetTensor(tensor_index, value)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 149, in SetTensor
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_SetTensor(self, i, value)
ValueError: Cannot set tensor: Got value of type NOTYPE but expected type FLOAT32 for input 3, name: decoder/one_hot/off_value 
```

If I roll back #2669, or explicitly pass `np.float32` to `np.array`,

```diff
$ git diff
diff --git a/tools/nnpackage_tool/gen_golden/gen_golden.py b/tools/nnpackage_tool/gen_golden/gen_golden.py
index d78e0a8..4373d8f 100755
--- a/tools/nnpackage_tool/gen_golden/gen_golden.py
+++ b/tools/nnpackage_tool/gen_golden/gen_golden.py
@@ -136,7 +136,7 @@ if __name__ == '__main__':
                 input_values.append(
                     np.array(np.random.randint(0, 255, this_shape, this_dtype)))
             elif this_dtype == np.float32:
-                input_values.append(np.array(np.random.random_sample(this_shape)))
+                input_values.append(np.array(np.random.random_sample(this_shape), np.float32))
             elif this_dtype == np.bool_:
                 # generate random integer from [0, 2)
                 input_values.append(
```

it is solved.

I am using `numpy 1.18.4` and `tf 2.2.0`.

cc @chunseoklee, @llFreetimell

Please note that `dtype` is not **numpy** type. It is **tensorflow**'s [`Tensor`](https://www.tensorflow.org/api_docs/python/tf/Tensor)'s dtype, though they are comparable with `==`.

**Comment by glistening** [comment]
I've investigated more. 

`np.random.random_sample` generates `float64` type of random number.
It doesn't matter whether array has 1 element or not.

```
$ python -c "import numpy; print(numpy.random.random_sample((2,3)).dtype)"
float64
$ python -c "import numpy; print(numpy.random.random_sample((1)).dtype)"
float64
```

_"ValueError: **Cannot set tensor: Got value of type NOTYPE but expected type FLOAT32** for input 3, name: decoder/one_hot/off_value"_ comes from `tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc`:

```c
  if (python_utils::TfLiteTypeFromPyArray(array) != tensor->type) {
    PyErr_Format(PyExc_ValueError,
                 "Cannot set tensor:"
                 " Got value of type %s"
                 " but expected type %s for input %d, name: %s ",
                 TfLiteTypeGetName(python_utils::TfLiteTypeFromPyArray(array)),
                 TfLiteTypeGetName(tensor->type), i, tensor->name);
    return nullptr;
  }
```

and `TfLiteTypeFromPyType` does not give name for `NPY_FLOAT64`.

```c
TfLiteType TfLiteTypeFromPyType(int py_type) {
  switch (py_type) {
    case NPY_FLOAT32:
      return kTfLiteFloat32;
    case NPY_FLOAT16:
      return kTfLiteFloat16;
    case NPY_INT32:
      return kTfLiteInt32;
    case NPY_INT16:
      return kTfLiteInt16;
    ...
  }
  return kTfLiteNoType;
}
```
It is the reason **NOTYPE** is shown.

Calling `np.array with `dtype` parameter of `np.float32` solves the problem.

------

@llFreetimell, @chunseoklee Could you please share what was problem that makes you push #2669?
I would like to check it works with my change for this issue.
