### ISSUE TITLE
[tf2tfliteV2] Mobilenet V2 conversion fail on daily package test

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#3272]
Daily package generation & test job fail: `mobilenet_v2_1.0_224` nnpackage generation test by using `tools/nnpackage_tool/nncc-tc-to-nnpkg-tc/nncc-tc-to-nnpkg-tc.sh`

Input/output info file:
```
$ cat mobilenet_v2_1.0_224.info 
input,  input:0,  TF_FLOAT,   [1,224,224,3]
output, MobilenetV2/Predictions/Reshape_1:0,  TF_FLOAT,   [1,1001]
```

command: `tools/nnpackage_tool/nncc-tc-to-nnpkg-tc/nncc-tc-to-nnpkg-tc.sh -o nnpkg-tcs -i models mobilenet_v2_1.0_224`
```
03:05:02  2020-07-18 03:04:43.566398: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
03:05:02  To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
03:05:02  2020-07-18 03:04:43.608157: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3096300000 Hz
03:05:02  2020-07-18 03:04:43.648506: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5a03930 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
03:05:02  2020-07-18 03:04:43.648563: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
03:05:03  2020-07-18 03:04:44.027042: I tensorflow/core/grappler/devices.cc:78] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
03:05:03  2020-07-18 03:04:44.027224: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
03:05:03  2020-07-18 03:04:44.110052: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816] Optimization results for grappler item: graph_to_optimize
03:05:03  2020-07-18 03:04:44.110105: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 0.008ms.
03:05:03  2020-07-18 03:04:44.110120: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
03:05:03  Traceback (most recent call last):
03:05:03    File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/tf2tfliteV2.py", line 198, in <module>
03:05:03      main()
03:05:03    File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/tf2tfliteV2.py", line 194, in main
03:05:03      _convert(flags[0])
03:05:03    File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/tf2tfliteV2.py", line 177, in _convert
03:05:03      _v2_convert(flags)
03:05:03    File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/tf2tfliteV2.py", line 169, in _v2_convert
03:05:03      tflite_model = converter.convert()
03:05:03    File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/venv/lib/python3.5/site-packages/tensorflow/lite/python/lite.py", line 1076, in convert
03:05:03      return super(TFLiteConverterV2, self).convert()
03:05:03    File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/venv/lib/python3.5/site-packages/tensorflow/lite/python/lite.py", line 900, in convert
03:05:03      self).convert(graph_def, input_tensors, output_tensors)
03:05:03    File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/venv/lib/python3.5/site-packages/tensorflow/lite/python/lite.py", line 633, in convert
03:05:03      **converter_kwargs)
03:05:03    File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/venv/lib/python3.5/site-packages/tensorflow/lite/python/convert.py", line 567, in toco_convert_impl
03:05:03      input_tensors, output_tensors, *args, **kwargs)
03:05:03    File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/venv/lib/python3.5/site-packages/tensorflow/lite/python/convert.py", line 458, in build_toco_convert_protos
03:05:03      for dim in shape:
03:05:03    File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/venv/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 859, in __iter__
03:05:03      raise ValueError("Cannot iterate over a shape with unknown rank.")
03:05:03  ValueError: Cannot iterate over a shape with unknown rank.
```

**Comment by seanshpark** [comment]
CC @mhs4670go

**Comment by seanshpark** [comment]
How do I reproduce this problem in my local?

**Comment by mhs4670go** [comment]
This is because `tf2nnpkg` runs `tf2tfliteV2` with `--v2` option which doesn't support unknown shape. Here are solutions I'm able to come up with.

1. Exclude unknown rank model
2. Runs `--v1` command if `--v2` command fails

Latter looks good for me.

**Comment by seanshpark** [comment]
> Runs --v1 command if --v2 command fails

👍

**Comment by hseok-oh** [comment]
@mhs4670go When I fixed `tf2nnpkg` manually to run `tf2tfliteV2` with `--v1`,  got similar failure

```
2020-07-20 11:39:27.753778: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-07-20 11:39:27.759248: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3096300000 Hz
2020-07-20 11:39:27.761382: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x451c370 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 11:39:27.761426: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/tf2tfliteV2.py", line 198, in <module>
    main()
  File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/tf2tfliteV2.py", line 194, in main
    _convert(flags[0])
  File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/tf2tfliteV2.py", line 175, in _convert
    _v1_convert(flags)
  File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/tf2tfliteV2.py", line 137, in _v1_convert
    tflite_model = converter.convert()
  File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/venv/lib/python3.5/site-packages/tensorflow/lite/python/lite.py", line 1970, in convert
    return super(TFLiteConverter, self).convert()
  File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/venv/lib/python3.5/site-packages/tensorflow/lite/python/lite.py", line 1330, in convert
    **converter_kwargs)
  File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/venv/lib/python3.5/site-packages/tensorflow/lite/python/convert.py", line 567, in toco_convert_impl
    input_tensors, output_tensors, *args, **kwargs)
  File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/venv/lib/python3.5/site-packages/tensorflow/lite/python/convert.py", line 458, in build_toco_convert_protos
    for dim in shape:
  File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/venv/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 859, in __iter__
    raise ValueError("Cannot iterate over a shape with unknown rank.")
ValueError: Cannot iterate over a shape with unknown rank.
```

**Comment by mhs4670go** [comment]
@hseok-oh Please try this one.
```shell
INPUT=$(awk -F, '/^input/ { print $2 }' ${INFO_FILE} | cut -d: -f1 | tr -d ' ' | paste -d, -s)
OUTPUT=$(awk -F, '/^output/ { print $2 }' ${INFO_FILE} | cut -d: -f1 | tr -d ' ' | paste -d, -s)

INPUT_SHAPES=$(grep ^input ${INFO_FILE} | cut -d "[" -f2 | cut -d "]" -f1)

# generate tflite file
python "${ROOT}/bin/tf2tfliteV2.py" --v1 --input_path ${GRAPHDEF_FILE} \
--output_path "${TMPDIR}/${MODEL_NAME}.tflite" \
--input_arrays ${INPUT} --input_shapes ${INPUT_SHAPES} \
--output_arrays ${OUTPUT}
```

**Comment by hseok-oh** [comment]
@mhs4670go Passed. Thanks.

Could you fix tf2nnpkg for 1) additional parameter to use `--v1` 2) additional parameter to use input shape info ?

**Comment by seanshpark** [comment]
@hseok-oh , can you please share how to test this in local?
- where do I gent this `mobilenet_v2_1.0_224` material?

```
$ ~/ml/ss/one.draft/build/debug/compiler/tf2nnpkg/tf2nnpkg --info ./mobilenet_v2_1.0_224.info --graphdef ./mobilenet_v2_1.4_224.pb -o nnpkg
Read './mobilenet_v2_1.0_224.info'
Read './mobilenet_v2_1.0_224.info' - Done
Import from './mobilenet_v2_1.4_224.pb'
Import from './mobilenet_v2_1.4_224.pb' - Done
Make output directory 'nnpkg'
Make output directory 'nnpkg' - Done
Make package directory 'nnpkg/mobilenet_v2_1.4_224'
Make package directory 'nnpkg/mobilenet_v2_1.4_224' - Done
Export into 'nnpkg/mobilenet_v2_1.4_224/mobilenet_v2_1.4_224.circle'
Export into 'nnpkg/mobilenet_v2_1.4_224/mobilenet_v2_1.4_224.circle' - Done
Make metadata directory 'nnpkg/mobilenet_v2_1.4_224/metadata'
Make metadata directory 'nnpkg/mobilenet_v2_1.4_224/metadata' - Done
Make manifest file 'nnpkg/mobilenet_v2_1.4_224/metadata/MANIFEST'
Make manifest file 'nnpkg/mobilenet_v2_1.4_224/metadata/MANIFEST' - Done
```

`tf2nnpkg` seems to work in my local.

**Comment by hseok-oh** [comment]
@seanshpark 
Test package: http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-publish-package/164/artifact/nncc-nightly-200718.tar.gz
Test models: http://npu.mooo.com/archive/nnpkg_test_model/tf_model_tc.tar.gz

Test

```
$ wget http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-publish-package/164/artifact/nncc-nightly-200718.tar.gz
$ wget http://npu.mooo.com/archive/nnpkg_test_model/tf_model_tc.tar.gz
$ tar -zxvf nncc-nightly-200718.tar.gz
$ mkdir -p models
$ tar -zxvf tf_model_tc.tar.gz -C models
$ export PATH=$PWD/bin:$PWD/bin/venv/bin:$PATH
$ [ONE_ROOT]/tools/nnpackage_tool/nncc-tc-to-nnpkg-tc/nncc-tc-to-nnpkg-tc.sh -o nnpkg-tcs -i models inception_v3
$ [ONE_ROOT]/tools/nnpackage_tool/nncc-tc-to-nnpkg-tc/nncc-tc-to-nnpkg-tc.sh -o nnpkg-tcs -i models mobilenet_v2_1.0_224
```

**Comment by seanshpark** [comment]
revise with both adding `--input_arrays ` and use `--v1` runs with no problem

**Comment by seanshpark** [comment]
```
16:49:54  [  Run  ] nnpkg-tcs/inception_v3 	Fail
16:49:54  
16:49:54  Error during model prepare : KernelGenerator: NYI for operation 'Shape'
16:49:54  
16:49:54  [Pipeline] }
```

**Comment by seanshpark** [comment]
@hseok-oh , @mhs4670go , can we first try with `--v1` then `--v2` ? `--v2` is necessary for control flow ops that will fail with `--v1`, so will be converted with `--v2`.

**Comment by seanshpark** [comment]
some contron flow ops can be converted with V1 so it's not feasable with V1 first ...

**Comment by seanshpark** [comment]
we may have to revise current test with explict version...

**Comment by seanshpark** [comment]
@hseok-oh , @mhs4670go , I've prepared #3396 
- we'll use v1 option for default and give `--v2` option if needed
- existing TCs should work, I think, with default `--v1` option when calling `tf2tfliteV2.py` script

**Comment by hseok-oh** [comment]
Test passed
