### ISSUE TITLE
Package test fail by tf2tfliteV2.py

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#4052]
```
17:16:39  
17:16:39  Traceback (most recent call last):
17:16:39    File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/tf2tfliteV2.py", line 18, in <module>
17:16:39      import tensorflow as tf
17:16:39    File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/venv/lib/python3.5/site-packages/tensorflow/__init__.py", line 33, in <module>
17:16:39      import distutils as _distutils
17:16:39    File "<frozen importlib._bootstrap>", line 969, in _find_and_load
17:16:39    File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
17:16:39    File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
17:16:39    File "<frozen importlib._bootstrap>", line 577, in module_from_spec
17:16:39    File "/home/jenkins_slave/workspace/nnfw/master/daily-publish-package/bin/venv/lib/python3.5/site-packages/_distutils_hack/__init__.py", line 82, in create_module
17:16:39      return importlib.import_module('._distutils', 'setuptools')
17:16:39    File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
17:16:39      return _bootstrap._gcd_import(name[level:], package, level)
17:16:39    File "<frozen importlib._bootstrap>", line 981, in _gcd_import
17:16:39    File "<frozen importlib._bootstrap>", line 931, in _sanity_check
```

http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-publish-package/211

cc/ @seanshpark @mhs4670go

**Comment by mhs4670go** [comment]
This's been solved by #4045. It will be passed in next test I think.

**Comment by hseok-oh** [comment]
@mhs4670go http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-publish-package/211 is includes change by #4045.

**Comment by hseok-oh** [comment]
Test script on CI:

```
tar -zxf build/archive/nncc-package.tar.gz
tar -zxf build/archive/nncc-venv-package.tar.gz

rm build/archive/*

export PATH=$PWD/bin:$PWD/bin/venv/bin:$PATH
tools/nnpackage_tool/nncc-tc-to-nnpkg-tc/nncc-tc-to-nnpkg-tc.sh -o nnpkg-tcs -i models inception_v3
tools/nnpackage_tool/nncc-tc-to-nnpkg-tc/nncc-tc-to-nnpkg-tc.sh -o nnpkg-tcs -i models mobilenet_v2_1.0_224
```

It don't use docker.

**Comment by seanshpark** [comment]
`daily-publish-package` now passed.
