### ISSUE TITLE
'select_operator.py' is not compatible with latest 'flatbuffers' package

### ISSUE THREAD

**Issue by cgbahk** [Samsung/ONE#7086]
With
```
$ pip list | grep -e flatbuffers -e numpy

flatbuffers (1.12)
numpy (1.19.5)
```
as recommended lowest version in https://github.com/Samsung/ONE/blob/0e03987e46deaea97d077bbcf6fa9f1c245cb207/tools/tflitefile_tool/requirements.txt#L1-L2

`select_operator.py` works as expected.

---
With latest `flatbuffers` package,
```
$ pip list | grep -e flatbuffers -e numpy

flatbuffers (2.0)
numpy (1.19.5)
```

`select_operator.py` fails for most trivial case.

### Example of regeneration
Model: `mobilenet_v1_1.0_224.tflite` in [TF Hosted](https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224.tgz)
Command: 
```
$ path/to/select_operator.py \
    mobilenet_v1_1.0_224.tflite \
    <(echo "0-1") \
    sliced.tflite

Input tensor(s): [6]
Output tensor(s): [4]
Traceback (most recent call last):
  File "/home/chbahk/r/ONE/tools/tflitefile_tool/select_operator.py", line 1423, in <module>
    main(args)
  File "/home/chbahk/r/ONE/tools/tflitefile_tool/select_operator.py", line 1391, in main
    used_buffers_dic, used_opcodes_dic, used_subgraphs_dic)
  File "/home/chbahk/r/ONE/tools/tflitefile_tool/select_operator.py", line 1219, in GenerateModel
    used_subgraphs_dic)
  File "/home/chbahk/r/ONE/tools/tflitefile_tool/select_operator.py", line 138, in GenerateOperatorCodes
    return new_builder.EndVector(new_operator_code_num)
TypeError: EndVector() takes 1 positional argument but 2 were given
```
Pdb log
```
(Pdb) c
Input tensor(s): [6]
Output tensor(s): [4]
Traceback (most recent call last):
  File "/usr/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/usr/lib/python3.6/bdb.py", line 434, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/chbahk/r/ONE/tools/tflitefile_tool/select_operator.py", line 17, in <module>
    import os
  File "/home/chbahk/r/ONE/tools/tflitefile_tool/select_operator.py", line 1391, in main
    used_buffers_dic, used_opcodes_dic, used_subgraphs_dic)
  File "/home/chbahk/r/ONE/tools/tflitefile_tool/select_operator.py", line 1219, in GenerateModel
    used_subgraphs_dic)
  File "/home/chbahk/r/ONE/tools/tflitefile_tool/select_operator.py", line 138, in GenerateOperatorCodes
    return new_builder.EndVector(new_operator_code_num)
TypeError: EndVector() takes 1 positional argument but 2 were given
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/chbahk/r/ONE/tools/tflitefile_tool/select_operator.py(138)GenerateOperatorCodes()
-> return new_builder.EndVector(new_operator_code_num)
(Pdb) new_operator_code_num
2
```

Regeneratable on random tflite, I guess.

**Comment by hseok-oh** [comment]
Length argument was removed, unfortunately.

https://github.com/google/flatbuffers/pull/6328

Tizen still uses flatbuffers v1.12. If we assume that this tool may used on desktop only, we can update this.

**Comment by hseok-oh** [comment]
Workaround #8214 resolved this issue.
