### ISSUE TITLE
[one-import-tf] Reproduce import problem with TF2.6.0

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#7591]
Let's make a python script to reproduce `one-import_neg_006.test` problem with TF2.6.0

This is to post an issue to tensorflow repo.

**Comment by seanshpark** [comment]
Refer https://github.com/Samsung/ONE/issues/7589#issuecomment-908819727

**Comment by seanshpark** [comment]
TF 2.3.0 error message:

> loc("InceptionV3/InceptionV3/Mixed_7c/concat"): error: 'tfl.concatenation' op failed to verify that values and output must have same element type
tf2tfliteV2.py: ConverterError: <unknown>:0: error: loc("InceptionV3/InceptionV3/Mixed_7c/concat"): 'tfl.concatenation' op failed to verify that values and output must have same element type
<unknown>:0: note: loc("InceptionV3/InceptionV3/Mixed_7c/concat"): see current operation: %0 = "tfl.concatenation"() {axis = 3 : i32, fused_activation_function = "NONE"} : () -> tensor<0x8x8x2048xf32>

**Comment by seanshpark** [comment]
Model
```
wget https://storage.googleapis.com/download.tensorflow.org/models/tflite/model_zoo/upload_20180427/inception_v3_2018_04_27.tgz
    tar zxvf inception_v3_2018_04_27.tgz
```
Working code
```py
import tensorflow as tf

input_path = "./inception_v3.pb"
output_path = "./inception_v3.tflite"

input_shapes = {"input": [1, 299, 299, 3]}
input_nodes = ["input"]
output_nodes = ["InceptionV3/Predictions/Reshape_1"]

converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
            input_path, input_nodes, output_nodes, input_shapes)
converter.allow_custom_ops = True
tflite_model = converter.convert()
open(output_path, "wb").write(tflite_model)
```

Invalid input shape for testing
```py
import tensorflow as tf

input_path = "./inception_v3.pb"
output_path = "./inception_v3.tflite"

input_shapes = {"input": [0, 299, 299, 3]}
input_nodes = ["input"]
output_nodes = ["InceptionV3/Predictions/Reshape_1"]

converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
            input_path, input_nodes, output_nodes, input_shapes)
converter.allow_custom_ops = True
tflite_model = converter.convert()
open(output_path, "wb").write(tflite_model)
```

Error message
> loc("InceptionV3/InceptionV3/Mixed_7c/concat"): error: 'tfl.concatenation' op failed to verify that values and output must have same element type
Traceback (most recent call last):
  File ".../tensorflow/lite/python/convert.py", line 199, in toco_convert_protos
    enable_mlir_converter)
  File ".../tensorflow/lite/python/wrap_toco.py", line 38, in wrapped_toco_convert
    enable_mlir_converter)
Exception: <unknown>:0: error: loc("InceptionV3/InceptionV3/Mixed_7c/concat"): 'tfl.concatenation' op failed to verify that values and output must have same element type
<unknown>:0: note: loc("InceptionV3/InceptionV3/Mixed_7c/concat"): see current operation: %0 = "tfl.concatenation"() {axis = 3 : i32, fused_activation_function = "NONE"} : () -> tensor<0x8x8x2048xf32>

**Comment by seanshpark** [comment]
done
