### ISSUE TITLE
[tflite2nnpkgtc] Error when executed in Virtual Box, Ubuntu 18.04 (solved)

### ISSUE THREAD

**Issue by kevin622** [Samsung/ONE#7607]
Hi. I am developing Circle-OpSelector in team COSMOS(#7596 here's our issue on the project).

When trying to run `tflite2nnpkgtc.sh` with input as `one/nnpackage/examples/v1.0.0/while_dynamic/while_dynamic.tflite`, I've recieved an error as such;
```shell
Traceback (most recent call last):
  File "tools/nnpackage_tool/gen_golden/gen_golden.py", line 118, in <module>
    interpreter = tf.lite.Interpreter(filename)
  File "/home/kevin/.local/lib/python3.6/site-packages/tensorflow/lite/python/interpreter.py", line 77, in __init__
    model_path))
ValueError: Op builtin_code out of range: 119. Are you using old TFLite binary with newer model?Registration failed.

model2nnpkg.sh: Generating nnpackage while_dynamic in temp
mv: 'input.h5'를 설명할 수 없음: 그런 파일이나 디렉터리가 없습니다
mv: 'expected.h5'를 설명할 수 없음: 그런 파일이나 디렉터리가 없습니다
```
I was running the file in __Virtual Box__, __Ubuntu 18.04__, and software conditions as such;
- Python 3.6.9
- pip 9.0.1
- tensorflow==1.14.0

The python and pip versions are the __default versions__ when Virtual Box is installed, and the `tensorflow` version is the latest version you can get when using pip 9.0.1.
So I've made a virtual environment for python and upgraded the version of pip.
```shell
$ python -m venv venv
$ source venv/bin/activate
(venv) $ pip install --upgrade pip
```
And then I installed `tensorflow` again in `venv`, updating my software conditions as such;
- Python 3.6.9
- pip 21.2.4
- tensorflow==2.6.0

And then the error was solved.

**Comment by kevin622** [comment]
Since this problem is solved, I'll close it rightaway.
