### ISSUE TITLE
unexpected keyword argument 'file_identifier'

### ISSUE THREAD

**Issue by cozcinar** [Samsung/ONE#8212]
Hello,

I am using `tools/tflitefile_tool/select_operator.py` and getting the following error:

```
Traceback (most recent call last):
  File "tools/tflitefile_tool/select_operator.py", line 1425, in <module>
    main(args)
  File "tools/tflitefile_tool/select_operator.py", line 1395, in main
    new_builder.Finish(new_model, file_identifier=b'TFL3')
TypeError: Finish() got an unexpected keyword argument 'file_identifier'
```

Also, when I removed `file_identifier=b'TFL3'` from new_builder.Finish function, I cannot open the model with netron

**Comment by hseok-oh** [comment]
`select_operator.py` requires `flatbuffers` >= 1.12. Could you check flatbuffers version?

For example, on my environment
```
$ pip3 show flatbuffers
Name: flatbuffers
Version: 2.0
Summary: The FlatBuffers serialization format for Python
Home-page: https://google.github.io/flatbuffers/
Author: FlatBuffers Contributors
Author-email: me@rwinslow.com
License: Apache 2.0
Location: /home/hseok82/.local/lib/python3.8/site-packages
Requires: 
Required-by: 
```

**Comment by hseok-oh** [comment]
I recommand to use `flatbuffers==1.12`. `select_operator.py` with `flatbuffers==2.0` has different issue.
